build:
  nodes:
    coverage:
      environment:
        python: 3.7.7
      tests:
        override:
          - command: 'pip install pipenv && pipenv install -d && pytest'
            coverage:
              file: '.coverage'
              format: 'py-cc'
