version: '3.7'

x-default-networks: &default-networks
  - stockspot

services:
    db:
      container_name: pandora-db
      image: mysql:5.7
      restart: always
      env_file: .env
      ports:
        - 3336:3306
      networks: *default-networks

    init-db:
      container_name: pandora-db-init
      image: pandora-api:local
      env_file: .env
      depends_on:
        - db
      links:
        - db:pandora_db
      command: ["docker-init.sh"]
      networks: *default-networks

    load-db-data:
      container_name: pandora-load-data
      image: pandora-api:local
      env_file: .env
      depends_on:
        - db
      links:
        - db:pandora_db
      command: ["load-resources"]
      networks: *default-networks

    api:
      container_name: pandora-api
      image: pandora-api:local
      depends_on:
        - init-db
      env_file: .env
      entrypoint: ["gunicorn"]
      command: [
        "--reload",
        "--timeout=1",
        "--worker-class=gthread",
        "--threads=3",
        "-b 0.0.0.0:8000",
        "--log-level=debug",
        "pandora.api.server:api"]
      links:
        - db:pandora_db
      networks: *default-networks
      ports:
        - 8020:8000
      restart: always
      volumes:
        - "${PWD}:/usr/local/pandora"

networks:
  stockspot:
    name: stockspot