"""add base tables

Revision ID: d72529ba39a3
Revises: 
Create Date: 2020-09-09 13:26:15.796007

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils.types import ScalarListType, EmailType

# revision identifiers, used by Alembic.
revision = 'd72529ba39a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('is_fruit', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('has_died', sa.Boolean(), nullable=True),
    sa.Column('eye_color', sa.String(length=32), nullable=True),
    sa.Column('email', EmailType(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('tags', ScalarListType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_employees',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'person_id')
    )
    op.create_table('person_foods',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'food_id')
    )
    op.create_table('person_friends',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'friend_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_friends')
    op.drop_table('person_foods')
    op.drop_table('company_employees')
    op.drop_table('persons')
    op.drop_table('foods')
    op.drop_table('companies')
    # ### end Alembic commands ###
